name: Release Artifact Bundle

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  release:
    name: Build and Upload Artifact Bundle
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"
      - name: Build universal binary
        run: swift build --disable-sandbox -c release --arch arm64 --arch x86_64
      - name: Create artifact bundle
        id: artifactbundle
        uses: giginet/github-action-artifactbundle@v2
        with:
          artifact_name: caspec
      - name: Upload artifact bundle to release
        run: |
          BODY="${{ github.event.release.body }}"
          BUNDLE_PATH="${{ steps.artifactbundle.outputs.bundle_path }}"
          SHA256="${{ steps.artifactbundle.outputs.bundle_sha256 }}"
          TAG_NAME="${{ github.event.release.tag_name }}"
          gh release upload "${TAG_NAME}" "${BUNDLE_PATH}"
          NEW_BODY="$(printf "%s\n%s" "$BODY" "$SHA256")"
          gh release edit "${TAG_NAME}" --notes "${NEW_BODY}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
